// SPDX-License-Identifier: MIT
pragma solidity ^0.8.19;

import {AccessControl} from "@openzeppelin/contracts/access/AccessControl.sol";

/**
 * @title Certificate
 * @dev Contract to represent and manage digital certificates
 */
contract Certificate is AccessControl {
    // Role definitions
    bytes32 public constant ADMIN_ROLE = keccak256("ADMIN_ROLE");
    bytes32 public constant ORGANIZATION_OWNER_ROLE = keccak256("ORGANIZATION_OWNER_ROLE");
    bytes32 public constant ORGANIZATION_MANAGER_ROLE = keccak256("ORGANIZATION_MANAGER_ROLE");

    enum CertificateStatus {
        Pending,
        Approved,
        Rejected,
        Revoked
    }

    struct CertificateData {
        string id;
        string organizationId;
        string certificateTypeId;
        CertificateStatus status;
        string holderIdCard;
        string holderCountryCode;
        uint256 grantLevel; // Level or points achieved
        uint256 issueTime;
        uint256 expireTime;
        string ipfsHash; // IPFS hash containing additional certificate data
        string rejectionReason;
        string revocationReason;
        address submittedBy; // Who submitted the certificate
    }

    // Events
    event CertificateSubmitted(
        string indexed id,
        string indexed organizationId,
        string indexed certificateTypeId,
        address submittedBy,
        string holderIdCard
    );
    event CertificateApproved(string indexed id, address indexed approvedBy);
    event CertificateRejected(string indexed id, address indexed rejectedBy, string reason);
    event CertificateRevoked(string indexed id, address indexed revokedBy, string reason);
    event CertificateRemoved(string indexed id, address indexed removedBy);

    // Storage
    mapping(string => CertificateData) private certificates;
    mapping(string => string[]) private organizationCertificates; // orgId => certificate IDs
    mapping(string => string[]) private typeCertificates; // typeId => certificate IDs
    mapping(string => string[]) private holderCertificates; // holderIdCard => certificate IDs
    mapping(CertificateStatus => string[]) private statusCertificates; // status => certificate IDs
    
    uint256 private certificateCounter;

    // Organization and CertificateType contract addresses
    address public organizationContract;
    address public certificateTypeContract;

    // Modifiers
    modifier onlyExistingCertificate(string memory _certId) {
        require(bytes(certificates[_certId].id).length > 0, "Certificate does not exist");
        _;
    }

    modifier onlyValidOrganization(string memory _orgId) {
        require(_isValidOrganization(_orgId), "Invalid or inactive organization");
        _;
    }

    modifier onlyValidCertificateType(string memory _typeId) {
        require(_isValidCertificateType(_typeId), "Invalid or inactive certificate type");
        _;
    }

    modifier onlyOrganizationMember(string memory _orgId) {
        require(_canManageOrganization(_orgId, msg.sender), "Not authorized for this organization");
        _;
    }

    constructor(
        address _admin,
        address _organizationContract,
        address _certificateTypeContract
    ) {
        _grantRole(DEFAULT_ADMIN_ROLE, _admin);
        _grantRole(ADMIN_ROLE, _admin);
        
        organizationContract = _organizationContract;
        certificateTypeContract = _certificateTypeContract;
    }

    /**
     * @dev Submit a new certificate for approval
     * @param _id Certificate ID (generated by backend)
     * @param _organizationId ID of the issuing organization
     * @param _certificateTypeId ID of the certificate type
     * @param _holderIdCard Holder's ID card number
     * @param _holderCountryCode Holder's country code
     * @param _grantLevel Level or points achieved
     * @param _expireTime Expiration timestamp
     * @param _ipfsHash IPFS hash containing additional certificate data
     */
    function submitCertificate(
        string memory _id,
        string memory _organizationId,
        string memory _certificateTypeId,
        string memory _holderIdCard,
        string memory _holderCountryCode,
        uint256 _grantLevel,
        uint256 _expireTime,
        string memory _ipfsHash
    ) external 
        onlyValidOrganization(_organizationId)
        onlyValidCertificateType(_certificateTypeId)
        onlyOrganizationMember(_organizationId)
    {
        require(bytes(_id).length > 0, "Certificate ID cannot be empty");
        require(bytes(certificates[_id].id).length == 0, "Certificate with this ID already exists");
        require(bytes(_holderIdCard).length > 0, "Holder ID card cannot be empty");
        require(bytes(_holderCountryCode).length > 0, "Holder country code cannot be empty");
        require(_expireTime > block.timestamp, "Expiration time must be in the future");
        require(bytes(_ipfsHash).length > 0, "IPFS hash cannot be empty");

        CertificateData storage cert = certificates[_id];
        cert.id = _id;
        cert.organizationId = _organizationId;
        cert.certificateTypeId = _certificateTypeId;
        cert.status = CertificateStatus.Pending;
        cert.holderIdCard = _holderIdCard;
        cert.holderCountryCode = _holderCountryCode;
        cert.grantLevel = _grantLevel;
        cert.expireTime = _expireTime;
        cert.ipfsHash = _ipfsHash;
        cert.submittedBy = msg.sender;

        // Add to tracking mappings
        organizationCertificates[_organizationId].push(_id);
        typeCertificates[_certificateTypeId].push(_id);
        holderCertificates[_holderIdCard].push(_id);
        statusCertificates[CertificateStatus.Pending].push(_id);

        certificateCounter++;

        emit CertificateSubmitted(_id, _organizationId, _certificateTypeId, msg.sender, _holderIdCard);
    }

    /**
     * @dev Approve a pending certificate (only admin)
     * @param _certId Certificate ID
     */
    function approveCertificate(string memory _certId) 
        external 
        onlyRole(ADMIN_ROLE) 
        onlyExistingCertificate(_certId) 
    {
        CertificateData storage cert = certificates[_certId];
        require(cert.status == CertificateStatus.Pending, "Certificate is not pending");

        cert.status = CertificateStatus.Approved;
        cert.issueTime = block.timestamp;

        // Update status tracking
        _removeFromStatusArray(CertificateStatus.Pending, _certId);
        statusCertificates[CertificateStatus.Approved].push(_certId);

        emit CertificateApproved(_certId, msg.sender);
    }

    /**
     * @dev Reject a pending certificate (only admin)
     * @param _certId Certificate ID
     * @param _reason Rejection reason
     */
    function rejectCertificate(string memory _certId, string memory _reason) 
        external 
        onlyRole(ADMIN_ROLE) 
        onlyExistingCertificate(_certId) 
    {
        CertificateData storage cert = certificates[_certId];
        require(cert.status == CertificateStatus.Pending, "Certificate is not pending");
        require(bytes(_reason).length > 0, "Rejection reason cannot be empty");

        cert.status = CertificateStatus.Rejected;
        cert.rejectionReason = _reason;

        // Update status tracking
        _removeFromStatusArray(CertificateStatus.Pending, _certId);
        statusCertificates[CertificateStatus.Rejected].push(_certId);

        emit CertificateRejected(_certId, msg.sender, _reason);
    }

    /**
     * @dev Revoke an approved certificate (only admin)
     * @param _certId Certificate ID
     * @param _reason Revocation reason
     */
    function revokeCertificate(string memory _certId, string memory _reason) 
        external 
        onlyExistingCertificate(_certId) 
    {
        CertificateData storage cert = certificates[_certId];
        require(cert.status == CertificateStatus.Approved, "Certificate is not approved");
        require(bytes(_reason).length > 0, "Revocation reason cannot be empty");
        
        // Allow either admin or organization manager to revoke
        require(
            hasRole(ADMIN_ROLE, msg.sender) || _canManageOrganization(cert.organizationId, msg.sender),
            "Not authorized to revoke this certificate"
        );

        cert.status = CertificateStatus.Revoked;
        cert.revocationReason = _reason;

        // Update status tracking
        _removeFromStatusArray(CertificateStatus.Approved, _certId);
        statusCertificates[CertificateStatus.Revoked].push(_certId);

        emit CertificateRevoked(_certId, msg.sender, _reason);
    }

    /**
     * @dev Remove a pending certificate (organization owners/managers only)
     * @param _certId Certificate ID
     */
    function removePendingCertificate(string memory _certId) 
        external 
        onlyExistingCertificate(_certId) 
    {
        CertificateData storage cert = certificates[_certId];
        require(cert.status == CertificateStatus.Pending, "Certificate is not pending");
        require(_canManageOrganization(cert.organizationId, msg.sender), "Not authorized for this organization");

        // Remove from all tracking mappings
        _removeFromOrganizationArray(cert.organizationId, _certId);
        _removeFromTypeArray(cert.certificateTypeId, _certId);
        _removeFromHolderArray(cert.holderIdCard, _certId);
        _removeFromStatusArray(CertificateStatus.Pending, _certId);

        // Delete the certificate
        delete certificates[_certId];

        emit CertificateRemoved(_certId, msg.sender);
    }

    // Internal functions
    function _isValidOrganization(string memory _orgId) private view returns (bool) {
        (bool success, bytes memory data) = organizationContract.staticcall(
            abi.encodeWithSignature("organizationExists(string)", _orgId)
        );
        if (!success || data.length == 0) return false;
        
        bool exists = abi.decode(data, (bool));
        if (!exists) return false;

        (success, data) = organizationContract.staticcall(
            abi.encodeWithSignature("isOrganizationActive(string)", _orgId)
        );
        if (!success || data.length == 0) return false;
        
        return abi.decode(data, (bool));
    }

    function _isValidCertificateType(string memory _typeId) private view returns (bool) {
        (bool success, bytes memory data) = certificateTypeContract.staticcall(
            abi.encodeWithSignature("certificateTypeExists(string)", _typeId)
        );
        if (!success || data.length == 0) return false;
        
        bool exists = abi.decode(data, (bool));
        if (!exists) return false;

        (success, data) = certificateTypeContract.staticcall(
            abi.encodeWithSignature("isCertificateTypeActive(string)", _typeId)
        );
        if (!success || data.length == 0) return false;
        
        return abi.decode(data, (bool));
    }

    function _canManageOrganization(string memory _orgId, address _account) private view returns (bool) {
        (bool success, bytes memory data) = organizationContract.staticcall(
            abi.encodeWithSignature("canManageOrganization(string,address)", _orgId, _account)
        );
        if (!success || data.length == 0) return false;
        
        return abi.decode(data, (bool));
    }

    function _removeFromStatusArray(CertificateStatus _status, string memory _certId) private {
        string[] storage statusArray = statusCertificates[_status];
        for (uint256 i = 0; i < statusArray.length; i++) {
            if (keccak256(bytes(statusArray[i])) == keccak256(bytes(_certId))) {
                statusArray[i] = statusArray[statusArray.length - 1];
                statusArray.pop();
                break;
            }
        }
    }

    function _removeFromOrganizationArray(string memory _orgId, string memory _certId) private {
        string[] storage orgArray = organizationCertificates[_orgId];
        for (uint256 i = 0; i < orgArray.length; i++) {
            if (keccak256(bytes(orgArray[i])) == keccak256(bytes(_certId))) {
                orgArray[i] = orgArray[orgArray.length - 1];
                orgArray.pop();
                break;
            }
        }
    }

    function _removeFromTypeArray(string memory _typeId, string memory _certId) private {
        string[] storage typeArray = typeCertificates[_typeId];
        for (uint256 i = 0; i < typeArray.length; i++) {
            if (keccak256(bytes(typeArray[i])) == keccak256(bytes(_certId))) {
                typeArray[i] = typeArray[typeArray.length - 1];
                typeArray.pop();
                break;
            }
        }
    }

    function _removeFromHolderArray(string memory _holderIdCard, string memory _certId) private {
        string[] storage holderArray = holderCertificates[_holderIdCard];
        for (uint256 i = 0; i < holderArray.length; i++) {
            if (keccak256(bytes(holderArray[i])) == keccak256(bytes(_certId))) {
                holderArray[i] = holderArray[holderArray.length - 1];
                holderArray.pop();
                break;
            }
        }
    }

    // View functions
    function getCertificate(string memory _certId) 
        external 
        view 
        onlyExistingCertificate(_certId) 
        returns (CertificateData memory) 
    {
        return certificates[_certId];
    }

    function getCertificatesByOrganization(string memory _orgId) 
        external 
        view 
        returns (string[] memory) 
    {
        return organizationCertificates[_orgId];
    }

    function getCertificatesByType(string memory _typeId) 
        external 
        view 
        returns (string[] memory) 
    {
        return typeCertificates[_typeId];
    }

    function getCertificatesByHolder(string memory _holderIdCard) 
        external 
        view 
        returns (string[] memory) 
    {
        return holderCertificates[_holderIdCard];
    }

    function getCertificatesByStatus(CertificateStatus _status) 
        external 
        view 
        returns (string[] memory) 
    {
        return statusCertificates[_status];
    }

    function certificateExists(string memory _certId) external view returns (bool) {
        return bytes(certificates[_certId].id).length > 0;
    }

    function getCertificateCount() external view returns (uint256) {
        return certificateCounter;
    }

    function isCertificateValid(string memory _certId) external view returns (bool) {
        if (bytes(certificates[_certId].id).length == 0) return false;
        
        CertificateData memory cert = certificates[_certId];
        return cert.status == CertificateStatus.Approved && 
               block.timestamp <= cert.expireTime;
    }

    // Admin functions to update contract addresses
    function updateOrganizationContract(address _newAddress) 
        external 
        onlyRole(ADMIN_ROLE) 
    {
        require(_newAddress != address(0), "Invalid address");
        organizationContract = _newAddress;
    }

    function updateCertificateTypeContract(address _newAddress) 
        external 
        onlyRole(ADMIN_ROLE) 
    {
        require(_newAddress != address(0), "Invalid address");
        certificateTypeContract = _newAddress;
    }
}
