// SPDX-License-Identifier: MIT
pragma solidity ^0.8.19;

import {AccessControl} from "@openzeppelin/contracts/access/AccessControl.sol";

/**
 * @title CertificateType
 * @dev Contract to represent and manage different types of certificates
 */
contract CertificateType is AccessControl {
    // Role definitions
    bytes32 public constant ADMIN_ROLE = keccak256("ADMIN_ROLE");

    struct CertificateTypeData {
        string id;
        string name;
        string code;
        string description;
        bool isActive;
        uint256 createdAt;
        uint256 updatedAt;
    }

    // Events
    event CertificateTypeCreated(string indexed id, string name, string code);
    event CertificateTypeUpdated(string indexed id, string name, string code, string description);
    event CertificateTypeDeactivated(string indexed id);

    // Storage
    mapping(string => CertificateTypeData) private certificateTypes;
    mapping(string => string) private codeToId; // Mapping from code to ID for uniqueness check
    
    uint256 private certificateTypeCounter;

    // Modifiers
    modifier onlyExistingCertificateType(string memory _typeId) {
        require(bytes(certificateTypes[_typeId].id).length > 0, "Certificate type does not exist");
        _;
    }

    modifier onlyActiveCertificateType(string memory _typeId) {
        require(certificateTypes[_typeId].isActive, "Certificate type is not active");
        _;
    }

    constructor(address _admin) {
        _grantRole(DEFAULT_ADMIN_ROLE, _admin);
        _grantRole(ADMIN_ROLE, _admin);
    }

    /**
     * @dev Creates a new certificate type (only admin can call this)
     * @param _id Certificate type ID (generated by backend)
     * @param _name Name of the certificate type
     * @param _code Unique code for the certificate type
     * @param _description Description of the certificate type
     */
    function createCertificateType(
        string memory _id,
        string memory _name,
        string memory _code,
        string memory _description
    ) external onlyRole(ADMIN_ROLE) {
        require(bytes(_id).length > 0, "Certificate type ID cannot be empty");
        require(bytes(_name).length > 0, "Certificate type name cannot be empty");
        require(bytes(_code).length > 0, "Certificate type code cannot be empty");
        require(bytes(certificateTypes[_id].id).length == 0, "Certificate type with this ID already exists");
        require(bytes(codeToId[_code]).length == 0, "Certificate type with this code already exists");

        CertificateTypeData storage certType = certificateTypes[_id];
        certType.id = _id;
        certType.name = _name;
        certType.code = _code;
        certType.description = _description;
        certType.isActive = true;
        certType.createdAt = block.timestamp;
        certType.updatedAt = block.timestamp;

        // Map code to ID for uniqueness enforcement
        codeToId[_code] = _id;

        certificateTypeCounter++;

        emit CertificateTypeCreated(_id, _name, _code);
    }

    /**
     * @dev Updates certificate type information (only admin can call this)
     * @param _typeId Certificate type ID
     * @param _name New name of the certificate type
     * @param _code New code for the certificate type
     * @param _description New description
     */
    function updateCertificateType(
        string memory _typeId,
        string memory _name,
        string memory _code,
        string memory _description
    ) external onlyRole(ADMIN_ROLE) onlyExistingCertificateType(_typeId) {
        require(bytes(_name).length > 0, "Certificate type name cannot be empty");
        require(bytes(_code).length > 0, "Certificate type code cannot be empty");

        CertificateTypeData storage certType = certificateTypes[_typeId];
        
        // If code is changing, check for uniqueness
        if (keccak256(bytes(certType.code)) != keccak256(bytes(_code))) {
            require(bytes(codeToId[_code]).length == 0, "Certificate type with this code already exists");
            
            // Remove old code mapping and add new one
            delete codeToId[certType.code];
            codeToId[_code] = _typeId;
        }

        certType.name = _name;
        certType.code = _code;
        certType.description = _description;
        certType.updatedAt = block.timestamp;

        emit CertificateTypeUpdated(_typeId, _name, _code, _description);
    }

    /**
     * @dev Deactivates a certificate type (only admin can call this)
     * @param _typeId Certificate type ID
     */
    function deactivateCertificateType(string memory _typeId) 
        external 
        onlyRole(ADMIN_ROLE) 
        onlyExistingCertificateType(_typeId) 
    {
        certificateTypes[_typeId].isActive = false;
        certificateTypes[_typeId].updatedAt = block.timestamp;

        emit CertificateTypeDeactivated(_typeId);
    }

    /**
     * @dev Reactivates a certificate type (only admin can call this)
     * @param _typeId Certificate type ID
     */
    function reactivateCertificateType(string memory _typeId) 
        external 
        onlyRole(ADMIN_ROLE) 
        onlyExistingCertificateType(_typeId) 
    {
        certificateTypes[_typeId].isActive = true;
        certificateTypes[_typeId].updatedAt = block.timestamp;
    }

    // View functions
    function getCertificateType(string memory _typeId) 
        external 
        view 
        onlyExistingCertificateType(_typeId) 
        returns (CertificateTypeData memory) 
    {
        return certificateTypes[_typeId];
    }

    function getCertificateTypeByCode(string memory _code) 
        external 
        view 
        returns (CertificateTypeData memory) 
    {
        string memory typeId = codeToId[_code];
        require(bytes(typeId).length > 0, "Certificate type with this code does not exist");
        return certificateTypes[typeId];
    }

    function certificateTypeExists(string memory _typeId) external view returns (bool) {
        return bytes(certificateTypes[_typeId].id).length > 0;
    }

    function isCertificateTypeActive(string memory _typeId) external view returns (bool) {
        return certificateTypes[_typeId].isActive;
    }

    function codeExists(string memory _code) external view returns (bool) {
        return bytes(codeToId[_code]).length > 0;
    }

    function getIdByCode(string memory _code) external view returns (string memory) {
        return codeToId[_code];
    }

    function getCertificateTypeCount() external view returns (uint256) {
        return certificateTypeCounter;
    }

    /**
     * @dev Get all active certificate types (for frontend display)
     * Note: This function is deprecated with string IDs. 
     * Consider implementing an array-based tracking system or pagination
     * to retrieve certificate types efficiently.
     */
    function getActiveCertificateTypes() external pure returns (CertificateTypeData[] memory) {
        // Return empty array since iteration over string IDs is not feasible
        // Applications should track certificate type IDs separately or use events
        return new CertificateTypeData[](0);
    }

    /**
     * @dev Get all certificate types (including inactive ones)
     * Note: This function is deprecated with string IDs.
     * Consider implementing an array-based tracking system or pagination
     * to retrieve certificate types efficiently.
     */
    function getAllCertificateTypes() external pure returns (CertificateTypeData[] memory) {
        // Return empty array since iteration over string IDs is not feasible
        // Applications should track certificate type IDs separately or use events
        return new CertificateTypeData[](0);
    }
}
