// SPDX-License-Identifier: MIT
pragma solidity ^0.8.19;

import {AccessControl} from "@openzeppelin/contracts/access/AccessControl.sol";

/**
 * @title Organization
 * @dev Contract to represent and manage educational certificate issuing organizations
 */
contract Organization is AccessControl {
    // Role definitions
    bytes32 public constant ADMIN_ROLE = keccak256("ADMIN_ROLE");
    bytes32 public constant ORGANIZATION_OWNER_ROLE = keccak256("ORGANIZATION_OWNER_ROLE");
    bytes32 public constant ORGANIZATION_MANAGER_ROLE = keccak256("ORGANIZATION_MANAGER_ROLE");

    struct OrganizationData {
        string id;
        address owner;
        string name;
        string countryCode;
        address[] managers;
        bool isActive;
        uint256 createdAt;
        uint256 updatedAt;
    }

    // Events
    event OrganizationCreated(string id, address owner, string name, string countryCode);
    event OrganizationUpdated(string id, string name, string countryCode);
    event OrganizationDeactivated(string id);
    event ManagerAdded(string orgId, address manager);
    event ManagerRemoved(string orgId, address manager);
    event OwnershipTransferred(string orgId, address previousOwner, address newOwner);

    // Storage
    mapping(string => OrganizationData) private organizations;
    mapping(string => mapping(address => bool)) private organizationManagers;
    mapping(address => string[]) private ownerOrganizations;
    mapping(address => string[]) private managerOrganizations;
    
    uint256 private organizationCounter;

    // Modifiers
    modifier onlyExistingOrganization(string memory _orgId) {
        require(bytes(organizations[_orgId].id).length > 0, "Organization does not exist");
        _;
    }

    modifier onlyOrganizationOwner(string memory _orgId) {
        require(
            organizations[_orgId].owner == msg.sender || hasRole(ADMIN_ROLE, msg.sender), 
            "Only organization owner can perform this action"
        );
        _;
    }

    modifier onlyOrganizationOwnerOrManager(string memory _orgId) {
        require(
            organizations[_orgId].owner == msg.sender || 
            organizationManagers[_orgId][msg.sender] ||
            hasRole(ADMIN_ROLE, msg.sender),
            "Only organization owner or manager can perform this action"
        );
        _;
    }

    modifier onlyActiveOrganization(string memory _orgId) {
        require(organizations[_orgId].isActive, "Organization is not active");
        _;
    }

    constructor(address _admin) {
        _grantRole(DEFAULT_ADMIN_ROLE, _admin);
        _grantRole(ADMIN_ROLE, _admin);
    }

    /**
     * @dev Creates a new organization (only admin can call this)
     * @param _id Organization ID (generated by backend)
     * @param _owner Address of the organization owner
     * @param _name Name of the organization
     * @param _countryCode Country code where the organization is located
     */
    function createOrganization(
        string memory _id,
        address _owner,
        string memory _name,
        string memory _countryCode
    ) external onlyRole(ADMIN_ROLE) {
        require(bytes(_id).length > 0, "Organization ID cannot be empty");
        require(_owner != address(0), "Owner address cannot be zero");
        require(bytes(_name).length > 0, "Organization name cannot be empty");
        require(bytes(_countryCode).length > 0, "Country code cannot be empty");
        require(bytes(organizations[_id].id).length == 0, "Organization with this ID already exists");

        OrganizationData storage org = organizations[_id];
        org.id = _id;
        org.owner = _owner;
        org.name = _name;
        org.countryCode = _countryCode;
        org.isActive = true;
        org.createdAt = block.timestamp;
        org.updatedAt = block.timestamp;

        // Grant organization owner role
        _grantRole(ORGANIZATION_OWNER_ROLE, _owner);
        
        // Track owner's organizations
        ownerOrganizations[_owner].push(_id);

        organizationCounter++;

        emit OrganizationCreated(_id, _owner, _name, _countryCode);
    }

    /**
     * @dev Updates organization information
     * @param _orgId Organization ID
     * @param _name New name of the organization
     * @param _countryCode New country code
     */
    function updateOrganization(
        string memory _orgId,
        string memory _name,
        string memory _countryCode
    ) external onlyExistingOrganization(_orgId) onlyOrganizationOwner(_orgId) {
        require(bytes(_name).length > 0, "Organization name cannot be empty");
        require(bytes(_countryCode).length > 0, "Country code cannot be empty");

        OrganizationData storage org = organizations[_orgId];
        org.name = _name;
        org.countryCode = _countryCode;
        org.updatedAt = block.timestamp;

        emit OrganizationUpdated(_orgId, _name, _countryCode);
    }

    /**
     * @dev Deactivates an organization (only admin can call this)
     * @param _orgId Organization ID
     */
    function deactivateOrganization(string memory _orgId) 
        external 
        onlyRole(ADMIN_ROLE) 
        onlyExistingOrganization(_orgId) 
    {
        organizations[_orgId].isActive = false;
        organizations[_orgId].updatedAt = block.timestamp;

        emit OrganizationDeactivated(_orgId);
    }

    /**
     * @dev Adds a manager to an organization
     * @param _orgId Organization ID
     * @param _manager Address of the manager to add
     */
    function addManager(string memory _orgId, address _manager) 
        external 
        onlyExistingOrganization(_orgId) 
        onlyOrganizationOwner(_orgId)
        onlyActiveOrganization(_orgId)
    {
        require(_manager != address(0), "Manager address cannot be zero");
        require(!organizationManagers[_orgId][_manager], "Manager already exists");
        require(_manager != organizations[_orgId].owner, "Owner cannot be added as manager");

        organizationManagers[_orgId][_manager] = true;
        organizations[_orgId].managers.push(_manager);
        organizations[_orgId].updatedAt = block.timestamp;

        // Grant organization manager role
        _grantRole(ORGANIZATION_MANAGER_ROLE, _manager);
        
        // Track manager's organizations
        managerOrganizations[_manager].push(_orgId);

        emit ManagerAdded(_orgId, _manager);
    }

    /**
     * @dev Removes a manager from an organization
     * @param _orgId Organization ID
     * @param _manager Address of the manager to remove
     */
    function removeManager(string memory _orgId, address _manager) 
        external 
        onlyExistingOrganization(_orgId) 
        onlyOrganizationOwner(_orgId) 
    {
        require(organizationManagers[_orgId][_manager], "Manager does not exist");

        organizationManagers[_orgId][_manager] = false;
        
        // Remove from managers array
        address[] storage managers = organizations[_orgId].managers;
        for (uint256 i = 0; i < managers.length; i++) {
            if (managers[i] == _manager) {
                managers[i] = managers[managers.length - 1];
                managers.pop();
                break;
            }
        }

        organizations[_orgId].updatedAt = block.timestamp;

        // Remove from manager's organizations tracking
        string[] storage managerOrgs = managerOrganizations[_manager];
        for (uint256 i = 0; i < managerOrgs.length; i++) {
            if (keccak256(bytes(managerOrgs[i])) == keccak256(bytes(_orgId))) {
                managerOrgs[i] = managerOrgs[managerOrgs.length - 1];
                managerOrgs.pop();
                break;
            }
        }

        emit ManagerRemoved(_orgId, _manager);
    }

    /**
     * @dev Transfers ownership of an organization (only admin can call this)
     * @param _orgId Organization ID
     * @param _newOwner New owner address
     */
    function transferOwnership(string memory _orgId, address _newOwner) 
        external 
        onlyRole(ADMIN_ROLE) 
        onlyExistingOrganization(_orgId) 
    {
        require(_newOwner != address(0), "New owner address cannot be zero");
        require(_newOwner != organizations[_orgId].owner, "New owner is the same as current owner");

        address previousOwner = organizations[_orgId].owner;
        organizations[_orgId].owner = _newOwner;
        organizations[_orgId].updatedAt = block.timestamp;

        // Update role assignments
        _revokeRole(ORGANIZATION_OWNER_ROLE, previousOwner);
        _grantRole(ORGANIZATION_OWNER_ROLE, _newOwner);

        // Update tracking
        string[] storage prevOwnerOrgs = ownerOrganizations[previousOwner];
        for (uint256 i = 0; i < prevOwnerOrgs.length; i++) {
            if (keccak256(bytes(prevOwnerOrgs[i])) == keccak256(bytes(_orgId))) {
                prevOwnerOrgs[i] = prevOwnerOrgs[prevOwnerOrgs.length - 1];
                prevOwnerOrgs.pop();
                break;
            }
        }
        ownerOrganizations[_newOwner].push(_orgId);

        emit OwnershipTransferred(_orgId, previousOwner, _newOwner);
    }

    // View functions
    function getOrganization(string memory _orgId) 
        external 
        view 
        onlyExistingOrganization(_orgId) 
        returns (OrganizationData memory) 
    {
        return organizations[_orgId];
    }

    function isOrganizationOwner(string memory _orgId, address _account) 
        external 
        view 
        onlyExistingOrganization(_orgId) 
        returns (bool) 
    {
        return organizations[_orgId].owner == _account;
    }

    function isOrganizationManager(string memory _orgId, address _account) 
        external 
        view 
        onlyExistingOrganization(_orgId) 
        returns (bool) 
    {
        return organizationManagers[_orgId][_account];
    }

    function canManageOrganization(string memory _orgId, address _account) 
        external 
        view 
        onlyExistingOrganization(_orgId) 
        returns (bool) 
    {
        return organizations[_orgId].owner == _account || organizationManagers[_orgId][_account];
    }

    function getOrganizationCount() external view returns (uint256) {
        return organizationCounter;
    }

    function getOwnerOrganizations(address _owner) external view returns (string[] memory) {
        return ownerOrganizations[_owner];
    }

    function getManagerOrganizations(address _manager) external view returns (string[] memory) {
        return managerOrganizations[_manager];
    }

    function organizationExists(string memory _orgId) external view returns (bool) {
        return bytes(organizations[_orgId].id).length > 0;
    }

    function isOrganizationActive(string memory _orgId) external view returns (bool) {
        return organizations[_orgId].isActive;
    }
}
