// SPDX-License-Identifier: MIT
pragma solidity ^0.8.19;

import {AccessControl} from "@openzeppelin/contracts/access/AccessControl.sol";
import {CertificateType} from "./contracts/CertificateType.sol";

/**
 * @title CertificationTypeManager
 * @dev Manager contract for certificate type operations with proper access control
 */
contract CertificationTypeManager is AccessControl {
    // Role definitions
    bytes32 public constant ADMIN_ROLE = keccak256("ADMIN_ROLE");

    // Events
    event CertificateTypeContractUpdated(address indexed oldContract, address indexed newContract);

    // Storage
    address public certificateTypeContract;
    
    modifier onlyValidCertificateTypeContract() {
        require(certificateTypeContract != address(0), "Certificate type contract not set");
        _;
    }

    constructor(address _admin, address _certificateTypeContract) {
        _grantRole(DEFAULT_ADMIN_ROLE, _admin);
        _grantRole(ADMIN_ROLE, _admin);
        
        certificateTypeContract = _certificateTypeContract;
    }

    /**
     * @dev Create a new certificate type (only admin)
     * @param _id Certificate type ID (generated by backend)
     * @param _name Name of the certificate type
     * @param _code Unique code for the certificate type
     * @param _description Description of the certificate type
     */
    function createCertificateType(
        string memory _id,
        string memory _name,
        string memory _code,
        string memory _description
    ) external onlyRole(ADMIN_ROLE) onlyValidCertificateTypeContract returns (string memory) {
        CertificateType(certificateTypeContract).createCertificateType(_id, _name, _code, _description);
        return _id;
    }

    /**
     * @dev Update certificate type information (only admin)
     * @param _typeId Certificate type ID
     * @param _name New name
     * @param _code New code
     * @param _description New description
     */
    function updateCertificateType(
        string memory _typeId,
        string memory _name,
        string memory _code,
        string memory _description
    ) external onlyRole(ADMIN_ROLE) onlyValidCertificateTypeContract {
        CertificateType(certificateTypeContract).updateCertificateType(_typeId, _name, _code, _description);
    }

    /**
     * @dev Deactivate a certificate type (only admin)
     * @param _typeId Certificate type ID
     */
    function deactivateCertificateType(string memory _typeId) 
        external 
        onlyRole(ADMIN_ROLE) 
        onlyValidCertificateTypeContract 
    {
        CertificateType(certificateTypeContract).deactivateCertificateType(_typeId);
    }

    /**
     * @dev Reactivate a certificate type (only admin)
     * @param _typeId Certificate type ID
     */
    function reactivateCertificateType(string memory _typeId) 
        external 
        onlyRole(ADMIN_ROLE) 
        onlyValidCertificateTypeContract 
    {
        CertificateType(certificateTypeContract).reactivateCertificateType(_typeId);
    }

    // View functions
    function getCertificateType(string memory _typeId) 
        external 
        view 
        onlyValidCertificateTypeContract 
        returns (CertificateType.CertificateTypeData memory) 
    {
        return CertificateType(certificateTypeContract).getCertificateType(_typeId);
    }

    function getCertificateTypeByCode(string memory _code) 
        external 
        view 
        onlyValidCertificateTypeContract 
        returns (CertificateType.CertificateTypeData memory) 
    {
        return CertificateType(certificateTypeContract).getCertificateTypeByCode(_code);
    }

    function certificateTypeExists(string memory _typeId) 
        external 
        view 
        onlyValidCertificateTypeContract 
        returns (bool) 
    {
        return CertificateType(certificateTypeContract).certificateTypeExists(_typeId);
    }

    function isCertificateTypeActive(string memory _typeId) 
        external 
        view 
        onlyValidCertificateTypeContract 
        returns (bool) 
    {
        return CertificateType(certificateTypeContract).isCertificateTypeActive(_typeId);
    }

    function codeExists(string memory _code) 
        external 
        view 
        onlyValidCertificateTypeContract 
        returns (bool) 
    {
        return CertificateType(certificateTypeContract).codeExists(_code);
    }

    function getIdByCode(string memory _code) 
        external 
        view 
        onlyValidCertificateTypeContract 
        returns (string memory) 
    {
        return CertificateType(certificateTypeContract).getIdByCode(_code);
    }

    function getCertificateTypeCount() 
        external 
        view 
        onlyValidCertificateTypeContract 
        returns (uint256) 
    {
        return CertificateType(certificateTypeContract).getCertificateTypeCount();
    }

    function getActiveCertificateTypes() 
        external 
        view 
        onlyValidCertificateTypeContract 
        returns (CertificateType.CertificateTypeData[] memory) 
    {
        return CertificateType(certificateTypeContract).getActiveCertificateTypes();
    }

    function getAllCertificateTypes() 
        external 
        view 
        onlyValidCertificateTypeContract 
        returns (CertificateType.CertificateTypeData[] memory) 
    {
        return CertificateType(certificateTypeContract).getAllCertificateTypes();
    }

    // Admin functions
    function updateCertificateTypeContract(address _newContract) 
        external 
        onlyRole(ADMIN_ROLE) 
    {
        require(_newContract != address(0), "Invalid contract address");
        require(_newContract != certificateTypeContract, "Same contract address");

        address oldContract = certificateTypeContract;
        certificateTypeContract = _newContract;

        emit CertificateTypeContractUpdated(oldContract, _newContract);
    }

    /**
     * @dev Get multiple certificate types by IDs (for batch operations)
     * @param _typeIds Array of certificate type IDs
     */
    function getCertificateTypes(string[] memory _typeIds) 
        external 
        view 
        onlyValidCertificateTypeContract 
        returns (CertificateType.CertificateTypeData[] memory) 
    {
        CertificateType.CertificateTypeData[] memory types = new CertificateType.CertificateTypeData[](_typeIds.length);
        
        for (uint256 i = 0; i < _typeIds.length; i++) {
            if (CertificateType(certificateTypeContract).certificateTypeExists(_typeIds[i])) {
                types[i] = CertificateType(certificateTypeContract).getCertificateType(_typeIds[i]);
            }
        }

        return types;
    }

    /**
     * @dev Check if multiple certificate types exist (for batch validation)
     * @param _typeIds Array of certificate type IDs
     */
    function certificateTypesExist(string[] memory _typeIds) 
        external 
        view 
        onlyValidCertificateTypeContract 
        returns (bool[] memory) 
    {
        bool[] memory exists = new bool[](_typeIds.length);
        
        for (uint256 i = 0; i < _typeIds.length; i++) {
            exists[i] = CertificateType(certificateTypeContract).certificateTypeExists(_typeIds[i]);
        }

        return exists;
    }

    /**
     * @dev Get certificate types by codes (for batch operations)
     * @param _codes Array of certificate type codes
     */
    function getCertificateTypesByCodes(string[] memory _codes) 
        external 
        view 
        onlyValidCertificateTypeContract 
        returns (CertificateType.CertificateTypeData[] memory) 
    {
        CertificateType.CertificateTypeData[] memory types = new CertificateType.CertificateTypeData[](_codes.length);
        
        for (uint256 i = 0; i < _codes.length; i++) {
            if (CertificateType(certificateTypeContract).codeExists(_codes[i])) {
                types[i] = CertificateType(certificateTypeContract).getCertificateTypeByCode(_codes[i]);
            }
        }

        return types;
    }

    /**
     * @dev Check if multiple codes exist (for batch validation)
     * @param _codes Array of certificate type codes
     */
    function codesExist(string[] memory _codes) 
        external 
        view 
        onlyValidCertificateTypeContract 
        returns (bool[] memory) 
    {
        bool[] memory exists = new bool[](_codes.length);
        
        for (uint256 i = 0; i < _codes.length; i++) {
            exists[i] = CertificateType(certificateTypeContract).codeExists(_codes[i]);
        }

        return exists;
    }

    /**
     * @dev Bulk create certificate types (only admin)
     * @param _ids Array of certificate type IDs
     * @param _names Array of names
     * @param _codes Array of codes
     * @param _descriptions Array of descriptions
     */
    function bulkCreateCertificateTypes(
        string[] memory _ids,
        string[] memory _names,
        string[] memory _codes,
        string[] memory _descriptions
    ) external onlyRole(ADMIN_ROLE) onlyValidCertificateTypeContract {
        require(_ids.length == _names.length, "Array length mismatch: ids and names");
        require(_names.length == _codes.length, "Array length mismatch: names and codes");
        require(_codes.length == _descriptions.length, "Array length mismatch: codes and descriptions");

        for (uint256 i = 0; i < _ids.length; i++) {
            CertificateType(certificateTypeContract).createCertificateType(
                _ids[i],
                _names[i],
                _codes[i],
                _descriptions[i]
            );
        }
    }

    /**
     * @dev Bulk deactivate certificate types (only admin)
     * @param _typeIds Array of certificate type IDs to deactivate
     */
    function bulkDeactivateCertificateTypes(string[] memory _typeIds) 
        external 
        onlyRole(ADMIN_ROLE) 
        onlyValidCertificateTypeContract 
    {
        for (uint256 i = 0; i < _typeIds.length; i++) {
            CertificateType(certificateTypeContract).deactivateCertificateType(_typeIds[i]);
        }
    }
}
