// SPDX-License-Identifier: MIT
pragma solidity ^0.8.19;

import {AccessControl} from "@openzeppelin/contracts/access/AccessControl.sol";
import {Organization} from "./contracts/Organization.sol";

/**
 * @title OrganizationManager
 * @dev Manager contract for organization operations with proper access control
 */
contract OrganizationManager is AccessControl {
    // Role definitions
    bytes32 public constant ADMIN_ROLE = keccak256("ADMIN_ROLE");

    // Events
    event OrganizationContractUpdated(address indexed oldContract, address indexed newContract);

    // Storage
    address public organizationContract;
    
    modifier onlyValidOrganizationContract() {
        require(organizationContract != address(0), "Organization contract not set");
        _;
    }

    constructor(address _admin, address _organizationContract) {
        _grantRole(DEFAULT_ADMIN_ROLE, _admin);
        _grantRole(ADMIN_ROLE, _admin);
        
        organizationContract = _organizationContract;
    }

    /**
     * @dev Register a new organization (only admin)
     * @param _id Organization ID (generated by backend)
     * @param _owner Address of the organization owner
     * @param _name Name of the organization
     * @param _countryCode Country code
     */
    function registerOrganization(
        string memory _id,
        address _owner,
        string memory _name,
        string memory _countryCode
    ) external onlyRole(ADMIN_ROLE) onlyValidOrganizationContract returns (string memory) {
        Organization(organizationContract).createOrganization(_id, _owner, _name, _countryCode);
        return _id;
    }

    /**
     * @dev Update organization information (only admin)
     * @param _orgId Organization ID
     * @param _name New name
     * @param _countryCode New country code
     */
    function updateOrganization(
        string memory _orgId,
        string memory _name,
        string memory _countryCode
    ) external onlyRole(ADMIN_ROLE) onlyValidOrganizationContract {
        // Get organization data to verify ownership
        Organization.OrganizationData memory orgData = Organization(organizationContract).getOrganization(_orgId);
        require(bytes(orgData.id).length > 0, "Organization does not exist");

        // Call the update function on the organization contract
        // Note: This requires the manager contract to have appropriate permissions
        Organization(organizationContract).updateOrganization(_orgId, _name, _countryCode);
    }

    /**
     * @dev Deactivate an organization (only admin)
     * @param _orgId Organization ID
     */
    function deactivateOrganization(string memory _orgId) 
        external 
        onlyRole(ADMIN_ROLE) 
        onlyValidOrganizationContract 
    {
        Organization(organizationContract).deactivateOrganization(_orgId);
    }

    /**
     * @dev Transfer ownership of an organization (only admin)
     * @param _orgId Organization ID
     * @param _newOwner New owner address
     */
    function transferOrganizationOwnership(string memory _orgId, address _newOwner) 
        external 
        onlyRole(ADMIN_ROLE) 
        onlyValidOrganizationContract 
    {
        Organization(organizationContract).transferOwnership(_orgId, _newOwner);
    }

    /**
     * @dev Add manager to organization (organization owner or admin)
     * @param _orgId Organization ID
     * @param _manager Manager address to add
     */
    function addOrganizationManager(string memory _orgId, address _manager) 
        external 
        onlyValidOrganizationContract 
    {
        require(
            hasRole(ADMIN_ROLE, msg.sender) || 
            Organization(organizationContract).isOrganizationOwner(_orgId, msg.sender),
            "Only admin or organization owner can add managers"
        );

        Organization(organizationContract).addManager(_orgId, _manager);
    }

    /**
     * @dev Remove manager from organization (organization owner or admin)
     * @param _orgId Organization ID
     * @param _manager Manager address to remove
     */
    function removeOrganizationManager(string memory _orgId, address _manager) 
        external 
        onlyValidOrganizationContract 
    {
        require(
            hasRole(ADMIN_ROLE, msg.sender) || 
            Organization(organizationContract).isOrganizationOwner(_orgId, msg.sender),
            "Only admin or organization owner can remove managers"
        );

        Organization(organizationContract).removeManager(_orgId, _manager);
    }

    // View functions
    function getOrganization(string memory _orgId) 
        external 
        view 
        onlyValidOrganizationContract 
        returns (Organization.OrganizationData memory) 
    {
        return Organization(organizationContract).getOrganization(_orgId);
    }

    function isOrganizationOwner(string memory _orgId, address _account) 
        external 
        view 
        onlyValidOrganizationContract 
        returns (bool) 
    {
        return Organization(organizationContract).isOrganizationOwner(_orgId, _account);
    }

    function isOrganizationManager(string memory _orgId, address _account) 
        external 
        view 
        onlyValidOrganizationContract 
        returns (bool) 
    {
        return Organization(organizationContract).isOrganizationManager(_orgId, _account);
    }

    function canManageOrganization(string memory _orgId, address _account) 
        external 
        view 
        onlyValidOrganizationContract 
        returns (bool) 
    {
        return Organization(organizationContract).canManageOrganization(_orgId, _account);
    }

    function getOrganizationCount() 
        external 
        view 
        onlyValidOrganizationContract 
        returns (uint256) 
    {
        return Organization(organizationContract).getOrganizationCount();
    }

    function getOwnerOrganizations(address _owner) 
        external 
        view 
        onlyValidOrganizationContract 
        returns (string[] memory) 
    {
        return Organization(organizationContract).getOwnerOrganizations(_owner);
    }

    function getManagerOrganizations(address _manager) 
        external 
        view 
        onlyValidOrganizationContract 
        returns (string[] memory) 
    {
        return Organization(organizationContract).getManagerOrganizations(_manager);
    }

    function organizationExists(string memory _orgId) 
        external 
        view 
        onlyValidOrganizationContract 
        returns (bool) 
    {
        return Organization(organizationContract).organizationExists(_orgId);
    }

    function isOrganizationActive(string memory _orgId) 
        external 
        view 
        onlyValidOrganizationContract 
        returns (bool) 
    {
        return Organization(organizationContract).isOrganizationActive(_orgId);
    }

    // Admin functions
    function updateOrganizationContract(address _newContract) 
        external 
        onlyRole(ADMIN_ROLE) 
    {
        require(_newContract != address(0), "Invalid contract address");
        require(_newContract != organizationContract, "Same contract address");

        address oldContract = organizationContract;
        organizationContract = _newContract;

        emit OrganizationContractUpdated(oldContract, _newContract);
    }

    /**
     * @dev Get multiple organizations by IDs (for batch operations)
     * @param _orgIds Array of organization IDs
     */
    function getOrganizations(string[] memory _orgIds) 
        external 
        view 
        onlyValidOrganizationContract 
        returns (Organization.OrganizationData[] memory) 
    {
        Organization.OrganizationData[] memory organizations = new Organization.OrganizationData[](_orgIds.length);
        
        for (uint256 i = 0; i < _orgIds.length; i++) {
            if (Organization(organizationContract).organizationExists(_orgIds[i])) {
                organizations[i] = Organization(organizationContract).getOrganization(_orgIds[i]);
            }
        }

        return organizations;
    }

    /**
     * @dev Check if multiple organizations exist (for batch validation)
     * @param _orgIds Array of organization IDs
     */
    function organizationsExist(string[] memory _orgIds) 
        external 
        view 
        onlyValidOrganizationContract 
        returns (bool[] memory) 
    {
        bool[] memory exists = new bool[](_orgIds.length);
        
        for (uint256 i = 0; i < _orgIds.length; i++) {
            exists[i] = Organization(organizationContract).organizationExists(_orgIds[i]);
        }

        return exists;
    }
}
